export const HTTP_REQUEST = 'HTTP_REQUEST';

export const USER_DETAILS_SET_FROM_STORAGE = 'USER_DETAILS_SET_FROM_STORAGE';

export const LOGOUT = 'LOGOUT';

export const LOGIN = 'LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PROFILE = 'PROFILE';
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

export const REGISTER_STEP_ONE = 'REGISTER_STEP_ONE';
export const REGISTER_STEP_ONE_REQUEST = 'REGISTER_STEP_ONE_REQUEST';
export const REGISTER_STEP_ONE_SUCCESS = 'REGISTER_STEP_ONE_SUCCESS';
export const REGISTER_STEP_ONE_FAILURE = 'REGISTER_STEP_ONE_FAILURE';

export const REGISTER_STEP_TWO = 'REGISTER_STEP_TWO';
export const REGISTER_STEP_TWO_REQUEST = 'REGISTER_STEP_TWO_REQUEST';
export const REGISTER_STEP_TWO_SUCCESS = 'REGISTER_STEP_TWO_SUCCESS';
export const REGISTER_STEP_TWO_FAILURE = 'REGISTER_STEP_TWO_FAILURE';

export const REGISTER_STEP_THREE = 'REGISTER_STEP_THREE';
export const REGISTER_STEP_THREE_REQUEST = 'REGISTER_STEP_THREE_REQUEST';
export const REGISTER_STEP_THREE_SUCCESS = 'REGISTER_STEP_THREE_SUCCESS';
export const REGISTER_STEP_THREE_FAILURE = 'REGISTER_STEP_THREE_FAILURE';

export const REGISTER_STEP_FOUR = 'REGISTER_STEP_FOUR';
export const REGISTER_STEP_FOUR_REQUEST = 'REGISTER_STEP_FOUR_REQUEST';
export const REGISTER_STEP_FOUR_SUCCESS = 'REGISTER_STEP_FOUR_SUCCESS';
export const REGISTER_STEP_FOUR_FAILURE = 'REGISTER_STEP_FOUR_FAILURE';

export const REGISTER_DATA = 'REGISTER_DATA';
export const REGISTER_DATA_REQUEST = 'REGISTER_DATA_REQUEST';
export const REGISTER_DATA_SUCCESS = 'REGISTER_DATA_SUCCESS';
export const REGISTER_DATA_FAILURE = 'REGISTER_DATA_FAILURE';

export const GET_REGIONS = 'GET_REGIONS';
export const GET_REGIONS_REQUEST = 'GET_REGIONS_REQUEST';
export const GET_REGIONS_SUCCESS = 'GET_REGIONS_SUCCESS';
export const GET_REGIONS_FAILURE = 'GET_REGIONS_FAILURE';

export const GET_DISTICK = 'GET_DISTICK';
export const GET_DISTICK_REQUEST = 'GET_DISTICK_REQUEST';
export const GET_DISTICK_SUCCESS = 'GET_DISTICK_SUCCESS';
export const GET_DISTICK_FAILURE = 'GET_DISTICK_FAILURE';

export const GET_TOWN = 'GET_TOWN';
export const GET_TOWN_REQUEST = 'GET_TOWN_REQUEST';
export const GET_TOWN_SUCCESS = 'GET_TOWN_SUCCESS';
export const GET_TOWN_FAILURE = 'GET_TOWN_FAILURE';

export const VERIFY_CODE = 'VERIFY_CODE';
export const VERIFY_CODE_REQUEST = 'VERIFY_CODE_REQUEST';
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_FAILURE = 'VERIFY_CODE_FAILURE';

export const DELETE_FILE = 'DELETE_FILE';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const SOCIAL_LOGIN = 'SOCIAL_LOGIN';
export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAILURE = 'SOCIAL_LOGIN_FAILURE';

export const GET_USER_CERTIFICATE = 'GET_USER_CERTIFICATE';
export const GET_USER_CERTIFICATE_REQUEST = 'GET_USER_CERTIFICATE_REQUEST';
export const GET_USER_CERTIFICATE_SUCCESS = 'GET_USER_CERTIFICATE_SUCCESS';
export const GET_USER_CERTIFICATE_FAILURE = 'GET_USER_CERTIFICATE_FAILURE';

export const GET_ADRESS_IDS = 'GET_ADRESS_IDS';
export const GET_ADRESS_IDS_REQUEST = 'GET_ADRESS_IDS_REQUEST';
export const GET_ADRESS_IDS_SUCCESS = 'GET_ADRESS_IDS_SUCCESS';
export const GET_ADRESS_IDS_FAILURE = 'GET_ADRESS_IDS_FAILURE';

export const OFF_NEW_BRANCH = 'OFF_NEW_BRANCH';

export const SUBMIT_BRANCH = 'SUBMIT_BRANCH';

export const SUBMIT_BENEFIT = 'SUBMIT_BENEFIT';

export const CONFIRMATION_DATA = 'CONFIRMATION_DATA';
export const CONFIRMATION_DATA_REQUEST = 'CONFIRMATION_DATA_REQUEST';
export const CONFIRMATION_DATA_SUCCESS = 'CONFIRMATION_DATA_SUCCESS';
export const CONFIRMATION_DATA_FAILURE = 'CONFIRMATION_DATA_FAILURE';

export const QUIZ_GET = 'QUIZ_GET';
export const QUIZ_GET_REQUEST = 'QUIZ_GET_REQUEST';
export const QUIZ_GET_SUCCESS = 'QUIZ_GET_SUCCESS';
export const QUIZ_GET_FAILURE = 'QUIZ_GET_FAILURE';
