export const HTTP_REQUEST = 'HTTP_REQUEST';

export const USER_DETAILS_SET_FROM_STORAGE = 'USER_DETAILS_SET_FROM_STORAGE';

export const LOGOUT = 'LOGOUT';

export const LOGIN = 'LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PROFILE = 'PROFILE';
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

export const REGISTER_STEP_ONE = 'REGISTER_STEP_ONE';
export const REGISTER_STEP_ONE_REQUEST = 'REGISTER_STEP_ONE_REQUEST';
export const REGISTER_STEP_ONE_SUCCESS = 'REGISTER_STEP_ONE_SUCCESS';
export const REGISTER_STEP_ONE_FAILURE = 'REGISTER_STEP_ONE_FAILURE';

export const REGISTER_STEP_TWO = 'REGISTER_STEP_TWO';
export const REGISTER_STEP_TWO_REQUEST = 'REGISTER_STEP_TWO_REQUEST';
export const REGISTER_STEP_TWO_SUCCESS = 'REGISTER_STEP_TWO_SUCCESS';
export const REGISTER_STEP_TWO_FAILURE = 'REGISTER_STEP_TWO_FAILURE';

export const REGISTER_STEP_THREE = 'REGISTER_STEP_THREE';
export const REGISTER_STEP_THREE_REQUEST = 'REGISTER_STEP_THREE_REQUEST';
export const REGISTER_STEP_THREE_SUCCESS = 'REGISTER_STEP_THREE_SUCCESS';
export const REGISTER_STEP_THREE_FAILURE = 'REGISTER_STEP_THREE_FAILURE';

export const REGISTER_STEP_FOUR = 'REGISTER_STEP_FOUR';
export const REGISTER_STEP_FOUR_REQUEST = 'REGISTER_STEP_FOUR_REQUEST';
export const REGISTER_STEP_FOUR_SUCCESS = 'REGISTER_STEP_FOUR_SUCCESS';
export const REGISTER_STEP_FOUR_FAILURE = 'REGISTER_STEP_FOUR_FAILURE';

export const REGISTER_DATA = 'REGISTER_DATA';
export const REGISTER_DATA_REQUEST = 'REGISTER_DATA_REQUEST';
export const REGISTER_DATA_SUCCESS = 'REGISTER_DATA_SUCCESS';
export const REGISTER_DATA_FAILURE = 'REGISTER_DATA_FAILURE';

export const GET_REGIONS = 'GET_REGIONS';
export const GET_REGIONS_REQUEST = 'GET_REGIONS_REQUEST';
export const GET_REGIONS_SUCCESS = 'GET_REGIONS_SUCCESS';
export const GET_REGIONS_FAILURE = 'GET_REGIONS_FAILURE';

export const GET_DISTICK = 'GET_DISTICK';
export const GET_DISTICK_REQUEST = 'GET_DISTICK_REQUEST';
export const GET_DISTICK_SUCCESS = 'GET_DISTICK_SUCCESS';
export const GET_DISTICK_FAILURE = 'GET_DISTICK_FAILURE';

export const GET_TOWN = 'GET_TOWN';
export const GET_TOWN_REQUEST = 'GET_TOWN_REQUEST';
export const GET_TOWN_SUCCESS = 'GET_TOWN_SUCCESS';
export const GET_TOWN_FAILURE = 'GET_TOWN_FAILURE';

export const VERIFY_CODE = 'VERIFY_CODE';
export const VERIFY_CODE_REQUEST = 'VERIFY_CODE_REQUEST';
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_FAILURE = 'VERIFY_CODE_FAILURE';

export const DELETE_FILE = 'DELETE_FILE';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const SOCIAL_LOGIN = 'SOCIAL_LOGIN';
export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAILURE = 'SOCIAL_LOGIN_FAILURE';

export const GET_USER_CERTIFICATE = 'GET_USER_CERTIFICATE';
export const GET_USER_CERTIFICATE_REQUEST = 'GET_USER_CERTIFICATE_REQUEST';
export const GET_USER_CERTIFICATE_SUCCESS = 'GET_USER_CERTIFICATE_SUCCESS';
export const GET_USER_CERTIFICATE_FAILURE = 'GET_USER_CERTIFICATE_FAILURE';

export const GET_ADRESS_IDS = 'GET_ADRESS_IDS';
export const GET_ADRESS_IDS_REQUEST = 'GET_ADRESS_IDS_REQUEST';
export const GET_ADRESS_IDS_SUCCESS = 'GET_ADRESS_IDS_SUCCESS';
export const GET_ADRESS_IDS_FAILURE = 'GET_ADRESS_IDS_FAILURE';

export const OFF_NEW_BRANCH = 'OFF_NEW_BRANCH';

export const SUBMIT_BRANCH = 'SUBMIT_BRANCH';

export const SUBMIT_BENEFIT = 'SUBMIT_BENEFIT';

export const CONFIRMATION_DATA = 'CONFIRMATION_DATA';
export const CONFIRMATION_DATA_REQUEST = 'CONFIRMATION_DATA_REQUEST';
export const CONFIRMATION_DATA_SUCCESS = 'CONFIRMATION_DATA_SUCCESS';
export const CONFIRMATION_DATA_FAILURE = 'CONFIRMATION_DATA_FAILURE';

export const QUIZ_GET = 'QUIZ_GET';
export const QUIZ_GET_REQUEST = 'QUIZ_GET_REQUEST';
export const QUIZ_GET_SUCCESS = 'QUIZ_GET_SUCCESS';
export const QUIZ_GET_FAILURE = 'QUIZ_GET_FAILURE';

export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const GET_PROFILE_INFO_REQUEST = 'GET_PROFILE_INFO_REQUEST';
export const GET_PROFILE_INFO_SUCCESS = 'GET_PROFILE_INFO_SUCCESS';
export const GET_PROFILE_INFO_FAILURE = 'GET_PROFILE_INFO_FAILURE';

export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';
export const UPDATE_USER_ADDRESS_REQUEST = 'UPDATE_USER_ADDRESS_REQUEST';
export const UPDATE_USER_ADDRESS_SUCCESS = 'UPDATE_USER_ADDRESS_SUCCESS';
export const UPDATE_USER_ADDRESS_FAILURE = 'UPDATE_USER_ADDRESS_FAILURE';

export const GET_USER_KEYS = 'GET_USER_KEYS';
export const GET_USER_KEYS_REQUEST = 'GET_USER_KEYS_REQUEST';
export const GET_USER_KEYS_SUCCESS = 'GET_USER_KEYS_SUCCESS';
export const GET_USER_KEYS_FAILURE = 'GET_USER_KEYS_FAILURE';

export const GET_MY_PROFILE_FILES = 'GET_MY_PROFILE_FILES';
export const GET_MY_PROFILE_FILES_REQUEST = 'GET_MY_PROFILE_FILES_REQUEST';
export const GET_MY_PROFILE_FILES_SUCCESS = 'GET_MY_PROFILE_FILES_SUCCESS';
export const GET_MY_PROFILE_FILES_FAILURE = 'GET_MY_PROFILE_FILES_FAILURE';

export const SET_PROFILE_UPDATE = 'SET_PROFILE_UPDATE';
export const SET_PROFILE_UPDATE_REQUEST = 'SET_PROFILE_UPDATE_REQUEST';
export const SET_PROFILE_UPDATE_SUCCESS = 'SET_PROFILE_UPDATE_SUCCESS';
export const SET_PROFILE_UPDATE_FAILURE = 'SET_PROFILE_UPDATE_FAILURE';

export const GET_PROFILE_UPDATE = 'GET_PROFILE_UPDATE';
export const GET_PROFILE_UPDATE_REQUEST = 'GET_PROFILE_UPDATE_REQUEST';
export const GET_PROFILE_UPDATE_SUCCESS = 'GET_PROFILE_UPDATE_SUCCESS';
export const GET_PROFILE_UPDATE_FAILURE = 'GET_PROFILE_UPDATE_FAILURE';

export const UPDATE_FILE = 'UPDATE_FILE';
export const UPDATE_FILE_REQUEST = 'UPDATE_FILE_REQUEST';
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS';
export const UPDATE_FILE_FAILURE = 'UPDATE_FILE_FAILURE';

export const SET_PASSWORD_UPDATE = 'SET_PASSWORD_UPDATE';
export const SET_PASSWORD_UPDATE_REQUEST = 'SET_PASSWORD_UPDATE_REQUEST';
export const SET_PASSWORD_UPDATE_SUCCESS = 'SET_PASSWORD_UPDATE_SUCCESS';
export const SET_PASSWORD_UPDATE_FAILURE = 'SET_PASSWORD_UPDATE_FAILURE';

export const GET_ACTIVITY_LIST = 'GET_ACTIVITY_LIST';
export const GET_ACTIVITY_LIST_REQUEST = 'GET_ACTIVITY_LIST_REQUEST';
export const GET_ACTIVITY_LIST_SUCCESS = 'GET_ACTIVITY_LIST_SUCCESS';
export const GET_ACTIVITY_LIST_FAILURE = 'GET_ACTIVITY_LIST_FAILURE';

export const GET_ALL_ACTIVITY_LIST = 'GET_ALL_ACTIVITY_LIST';
export const GET_ALL_ACTIVITY_LIST_REQUEST = 'GET_ALL_ACTIVITY_LIST_REQUEST';
export const GET_ALL_ACTIVITY_LIST_SUCCESS = 'GET_ALL_ACTIVITY_LIST_SUCCESS';
export const GET_ALL_ACTIVITY_LIST_FAILURE = 'GET_ALL_ACTIVITY_LIST_FAILURE';

export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const UPDATE_ACTIVITY_REQUEST = 'UPDATE_ACTIVITY_REQUEST';
export const UPDATE_ACTIVITY_SUCCESS = 'UPDATE_ACTIVITY_SUCCESS';
export const UPDATE_ACTIVITY_FAILURE = 'UPDATE_ACTIVITY_FAILURE';

export const ADD_NEW_ACTIVITY = 'ADD_NEW_ACTIVITY';
export const ADD_NEW_ACTIVITY_REQUEST = 'ADD_NEW_ACTIVITY_REQUEST';
export const ADD_NEW_ACTIVITY_SUCCESS = 'ADD_NEW_ACTIVITY_SUCCESS';
export const ADD_NEW_ACTIVITY_FAILURE = 'ADD_NEW_ACTIVITY_FAILURE';

export const GET_PT_BRANCH = 'GET_PT_BRANCH';
export const GET_PT_BRANCH_REQUEST = 'GET_PT_BRANCH_REQUEST';
export const GET_PT_BRANCH_SUCCESS = 'GET_PT_BRANCH_SUCCESS';
export const GET_PT_BRANCH_FAILURE = 'GET_PT_BRANCH_FAILURE';

export const GET_PT_ALL_BRANCH = 'GET_PT_ALL_BRANCH';
export const GET_PT_ALL_BRANCH_REQUEST = 'GET_PT_ALL_BRANCH_REQUEST';
export const GET_PT_ALL_BRANCH_SUCCESS = 'GET_PT_ALL_BRANCH_SUCCESS';
export const GET_PT_ALL_BRANCH_FAILURE = 'GET_PT_ALL_BRANCH_FAILURE';

export const UPDATE_PT_BRANCH = 'UPDATE_PT_BRANCH';
export const UPDATE_PT_BRANCH_REQUEST = 'UPDATE_PT_BRANCH_REQUEST';
export const UPDATE_PT_BRANCH_SUCCESS = 'UPDATE_PT_BRANCH_SUCCESS';
export const UPDATE_PT_BRANCH_FAILURE = 'UPDATE_PT_BRANCH_FAILURE';

export const ADD_NEW_PT_BRANCH = 'ADD_NEW_PT_BRANCH';
export const ADD_NEW_PT_BRANCH_REQUEST = 'ADD_NEW_PT_BRANCH_REQUEST';
export const ADD_NEW_PT_BRANCH_SUCCESS = 'ADD_NEW_PT_BRANCH_SUCCESS';
export const ADD_NEW_PT_BRANCH_FAILURE = 'ADD_NEW_PT_BRANCH_FAILURE';

export const GET_FAVORITE_USERS = 'GET_FAVORITE_USERS';
export const GET_FAVORITE_USERS_REQUEST = 'GET_FAVORITE_USERS_REQUEST';
export const GET_FAVORITE_USERS_SUCCESS = 'GET_FAVORITE_USERS_SUCCESS';
export const GET_FAVORITE_USERS_FAILURE = 'GET_FAVORITE_USERS_FAILURE';

export const GET_PROFICIENCY = 'GET_PROFICIENCY';
export const GET_PROFICIENCY_REQUEST = 'GET_PROFICIENCY_REQUEST';
export const GET_PROFICIENCY_SUCCESS = 'GET_PROFICIENCY_SUCCESS';
export const GET_PROFICIENCY_FAILURE = 'GET_PROFICIENCY_FAILURE';

export const ADD_PROFICIENCY = 'ADD_PROFICIENCY';
export const ADD_PROFICIENCY_REQUEST = 'ADD_PROFICIENCY_REQUEST';
export const ADD_PROFICIENCY_SUCCESS = 'ADD_PROFICIENCY_SUCCESS';
export const ADD_PROFICIENCY_FAILURE = 'ADD_PROFICIENCY_FAILURE';

export const ADD_FAVORITE_USER = 'ADD_FAVORITE_USER';
export const REMOVE_FAVORITE_USER = 'REMOVE_FAVORITE_USER';

export const GET_DIETITIAN_PRICE = 'GET_DIETITIAN_PRICE';
export const GET_DIETITIAN_PRICE_REQUEST = 'GET_DIETITIAN_PRICE_REQUEST';
export const GET_DIETITIAN_PRICE_SUCCESS = 'GET_DIETITIAN_PRICE_SUCCESS';
export const GET_DIETITIAN_PRICE_FAILURE = 'GET_DIETITIAN_PRICE_FAILURE';

export const UPDATE_DIETITIAN_PRICE = 'UPDATE_DIETITIAN_PRICE';
export const UPDATE_DIETITIAN_PRICE_REQUEST = 'UPDATE_DIETITIAN_PRICE_REQUEST';
export const UPDATE_DIETITIAN_PRICE_SUCCESS = 'UPDATE_DIETITIAN_PRICE_SUCCESS';
export const UPDATE_DIETITIAN_PRICE_FAILURE = 'UPDATE_DIETITIAN_PRICE_FAILURE';

export const GET_MY_GALLERIES = 'GET_MY_GALLERIES';
export const GET_MY_GALLERIES_REQUEST = 'GET_MY_GALLERIES_REQUEST';
export const GET_MY_GALLERIES_SUCCESS = 'GET_MY_GALLERIES_SUCCESS';
export const GET_MY_GALLERIES_FAILURE = 'GET_MY_GALLERIES_FAILURE';

export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOMS_REQUEST = 'GET_ROOMS_REQUEST';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAILURE = 'GET_ROOMS_FAILURE';

export const ADD_TYPE_CREATE = 'ADD_TYPE_CREATE';
export const ADD_TYPE_CREATE_REQUEST = 'ADD_TYPE_CREATE_REQUEST';
export const ADD_TYPE_CREATE_SUCCESS = 'ADD_TYPE_CREATE_SUCCESS';
export const ADD_TYPE_CREATE_FAILURE = 'ADD_TYPE_CREATE_FAILURE';

export const GET_TYPES = 'GET_TYPES';
export const GET_TYPES_REQUEST = 'GET_TYPES_REQUEST';
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';
export const GET_TYPES_FAILURE = 'GET_TYPES_FAILURE';
