export const TYPES = {
    FETCH_PENDING_VERIFTY: "FETCH_PENDING_VERIFTY",
    FETCH_SUCCESS_VERIFTY: "FETCH_SUCCESS_VERIFTY",
    FETCH_RESULT_VERIFTY: "FETCH_RESULT_VERIFTY",
    FETCH_RESPONSE_VERIFTY: "FETCH_RESPONSE_VERIFTY",
    FETCH_LIST_SUCCESS_VERIFTY: "FETCH_LIST_SUCCESS_VERIFTY",
    FETCH_UPDATE_SUCCESS_VERIFTY: "FETCH_UPDATE_SUCCESS_VERIFTY",
    FETCH_CREATE_VERIFTY: "FETCH_CREATE_VERIFTY",
    FETCH_ERROR_VERIFTY: "FETCH_ERROR_VERIFTY",
  };