export { default as Svg } from './statics/svg';
export * from './CommonStyles/Common.styles';
export * from './common';
export { default as ProtectedRoute } from './ProtectedRoute/ProtectedRoute';
export { default as Slider } from './MaterialSlider/MaterialSlider';
export { default as InputText } from './inputs/InputText';
export { default as Stars } from './Stars/Stars';
export { default as AwesomeIcon } from './statics/icon';
export { default as Main } from './Main';
export { default as CalendarCell } from './CalendarCell/CalendarCell';
export { default as Header } from './Header';
export { default as GoogleMapClusterer } from './GoogleMaps';
export { default as Button } from './buttons/button';
export { default as IconLabel } from './buttons/icon-label';
export { default as Text } from './typography/Text';
export { default as Title } from './typography/Titles';
export { default as LabelText } from './typography/LabelText';
export { default as FormPages } from './FormPages';
export { default as StepBar } from './steps/StepBar';
export { default as MacroMap } from './MacroMap';
export { default as LocationCard } from './LocationCard/LocationCard';
export { default as MacroCollections } from './MacroCollections';
export { default as DefBackground } from './statics/background';
export { default as Agreement } from './Confirmations/Agreement';
export { default as Privacy } from './Confirmations/Privacy';
export { default as Permission } from './Confirmations/Permission';
export { default as Information } from './Confirmations/Information';
export { Material } from './inputs/material';
export { default as Span } from './Span/Span';
export { default as SubTabs } from './SubTabs/SubTabs';
export { default as Files } from './ProfileSettings/Files/Files';
export { default as ActivityCard } from './ActivityCard';
export { default as FacilityCard } from './FacilityCard';
export { default as DietitianPriceCard } from './DietitianPriceCard/DietitianPriceCard';
export { default as CancellationFinalize } from './ProfileSettings/ProfileCancellation/CancellationFinalize';
export { default as CancellationReason } from './ProfileSettings/ProfileCancellation/CancellationReason';
export { default as CancellationDismissInfo } from './ProfileSettings/ProfileCancellation/CancellationDismissInfo';
export { default as PlusButton } from './buttons/PlusButton';
export { default as MinusButton } from './buttons/MinusButton';
export { default as ReservationHourButton } from './buttons/ReservationHourButton';
export { default as Select } from './Select/Select';
export { default as SearchInput } from './inputs/SearchInput';
export { default as HomeUserSlider } from './sliders/HomeUserSlider';

/*
export { default as SocialLogin } from './SocialLogin/SocialLogin';
*/
export { default as Tab } from './Tabs/Tabs';
export { default as Certificate } from './Certificate/Certificate';
export { default as ProfileCard } from './banner/profile-banner/ProfileCard';
export { default as MasonaryGallery } from './MasonaryGallery';
export { default as WorkPlaceRow } from './WorkPlaceRow/WorkPlaceRow';
export { default as HeaderLogin } from './AuthorizedHeader/AuthorizedHeader';
export { default as Wallet } from './Wallet';
export { default as SessionType } from './SessionType';
export { default as Packets } from './Packets';
export { default as Lessons } from './Lessons';
export { default as AddExercise } from './AddExercise';
export { default as ApproveCard } from './ApproveCard';
export { default as ApproveModal } from './ApproveModal';
export { default as RejectModal } from './RejectModal';
export { default as RateModal } from './RateModal';

export { default as CustomProgress } from './CustomProgress';
export { default as Tabbar } from './Tabbar';

export { default as GoogleAppZoom } from './GoogleMaps/index';
export { default as Blog } from './Blog';
export { default as BlogCartList } from './Blog/BlogCartList';
export { default as CashTransfer } from './CashTransfer';
export { default as CashTransferConfirm } from './CashTransferConfirm';
