export const TYPES = {
    FETCH_PENDING: "FETCH_PENDING_JP_PLACEHOLDER",
    FETCH_SUCCESS: "FETCH_SUCCESS_JP_PLACEHOLDER",
    FETCH_LIST_SUCCESS: "FETCH_LIST_SUCCESS_JP_PLACEHOLDER",
    FETCH_UPDATE_SUCCESS: "FETCH_UPDATE_SUCCESS_JP_PLACEHOLDER",
    FETCH_ERROR: "FETCH_ERROR_JP_PLACEHOLDER",
  };