export const TYPES = {
    FETCH_PENDING: "FETCH_PENDING",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_LIST_SUCCESS: "FETCH_LIST_SUCCESS",
    FETCH_UPDATE_SUCCESS: "FETCH_UPDATE_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR",
  };