export const TYPES = {
    FETCH_PENDING_JP_PLACEHOLDER: "FETCH_PENDING_JP_PLACEHOLDER",
    FETCH_SUCCESS_JP_PLACEHOLDER: "FETCH_SUCCESS_JP_PLACEHOLDER",
    FETCH_LIST_SUCCESS_JP_PLACEHOLDER: "FETCH_LIST_SUCCESS_JP_PLACEHOLDER",
    FETCH_UPDATE_SUCCESS_JP_PLACEHOLDER: "FETCH_UPDATE_SUCCESS_JP_PLACEHOLDER",
    FETCH_ERROR_JP_PLACEHOLDER: "FETCH_ERROR_JP_PLACEHOLDER",
  };