export const Pt = [
  {
    id: 1,
    image: require('../../assets/pt-groups/item-1/04.jpg'),
    name: 'Efe Parlak',
    category: 'Fitness Eğitmeni',
    price: '100',
    stars: '3',
    content: '',
    ctn: '[Meditasyon, Pilates, Fitness]',
    location: 'İstanbul, Beşiktaş',
    team: 'B',
  },
  {
    id: 2,
    image: require('../../assets/pt-groups/item-2/05.jpg'),
    name: 'Hazal Parlak',
    category: 'Fitness Eğitmeni',
    price: '100',
    stars: '5',
    content: '',
    ctn: '[Meditasyon, Pilates, Fitness]',
    location: 'İstanbul, Beşiktaş',
    team: 'A',
  },
  {
    id: 3,
    image: require('../../assets/pt-groups/item-3/07.jpg'),
    name: 'Efe Kurt',
    category: 'Fitness Eğitmeni',
    price: '100',
    stars: '4',
    content: '',
    ctn: '[Meditasyon, Pilates, Fitness]',
    location: 'İstanbul, Beşiktaş',
    team: 'B',
  },
  {
    id: 4,
    image: require('../../assets/pt-groups/item-4/06.jpg'),
    name: 'Ayşe Kaplan',
    category: 'Fitness Eğitmeni',
    price: '100',
    stars: '4',
    content: '',
    ctn: '[Meditasyon, Pilates, Fitness]',
    location: 'Ankara, Çankaya',
    team: 'C',
  },
];

export const Packets = [
  {
    id: 1,
    image: require('../../assets/packets/item-2/02.jpg'),
    name: 'Sağlıklı Yaşa',
    category: 'Fitness',
    price: '120',
    time: '10',
    content: 'Fitness',
    authorType: 'EĞİTMEN',
    author: '',
    package_included: '10',
    class: 'A',
  },
  {
    id: 2,
    image: require('../../assets/activityPicture.png'),
    name: 'Kilo Ver',
    category: 'Fitness',
    price: '120',
    time: '10',
    content: 'Fitness',
    authorType: 'EĞİTMEN',
    author: '',
    package_included: '10',
    class: 'A',
  },
  {
    id: 3,
    image: require('../../assets/packets/item-4/04.jpg'),
    name: 'Fit Ol',
    category: 'Fitness',
    price: '120',
    time: '10',
    content: 'Fitness',
    authorType: 'EĞİTMEN',
    author: '',
    package_included: '10',
    class: 'A',
  },
];

export const Gym = [
  {
    id: 1,
    image: require('../../assets/gym/item-1/01.jpg'),
    name: 'Bfit studio',
    title: 'Crossfit',
    category: 'Boks, Pilates, Fitness',
    price: '200',
    capasity: '100',
    square_meters: '180',
    content: '',
    categories: ['Meditasyon', 'Pilates', 'Fitness'],
    location: 'İstanbul, Beşiktaş',
    star: 5,
  },
  {
    id: 2,
    image: require('../../assets/gym/item-2/02.jpg'),
    name: 'Fighting fit studio',
    title: 'Crossfit',
    category: 'yoga,meditasyon,tenis',
    price: '180',
    capasity: '90',
    square_meters: '180',
    content: '',
    categories: 'yoga,meditasyon,tenis',
    location: 'İstanbul, Beşiktaş, Cadde',
    star: 5,
  },
  {
    id: 3,
    image: require('../../assets/gym/item-3/03.jpg'),
    name: 'Wind Life Studio',
    title: 'Crossfit',
    category: 'Fitness,Pilates,tenis',
    price: '80',
    capasity: '90',
    square_meters: '180',
    content: '',
    categories: 'yoga,meditasyon,tenis',
    location: 'İstanbul, Beşiktaş',
    star: 5,
  },
  {
    id: 4,
    image: require('../../assets/gym/item-4/04.jpg'),
    name: 'Wind Life Studio',
    title: 'Crossfit',
    category: 'Fitness,Pilates,tenis',
    price: '80',
    capasity: '90',
    square_meters: '180',
    content: '',
    categories: 'Fitness,Pilates,tenis',
    location: 'İstanbul, Beşiktaş',
    star: 5,
  },
];

export const GroupLesson = [
  {
    id: 1,
    image: require('../../assets/group-lesson/item-1/01.jpg'),
    name: 'İnci Coşkun',
    category: 'Salon B Fit Studio',
    price: '1.300',
    star: '5',
    date: '30 Mar. 14:00',
    content: 'Pilates Eğitmeni',
    location: 'İstanbul, Beşiktaş',
    ctn: 'Pilates',
    seater: '3/8',
  },
  {
    id: 2,
    image: require('../../assets/group-lesson/item-2/02.jpg'),
    name: 'Fatih Kale',
    category: 'Salon Figt Night Fit Cl…',
    price: '2.000',
    star: '5',
    date: '03 Şub. 15:00',
    content: 'Box Eğitmeni',
    location: 'İstanbul, Beşiktaş',
    ctn: 'Boks',
    seater: '2/6',
  },
  {
    id: 3,
    image: require('../../assets/group-lesson/item-3/03.jpg'),
    name: 'Murat Öztürk',
    category: 'Salon Best Of Fitness',
    price: '2000',
    star: '5',
    date: '05 May. 16:00',
    content: 'Fitness Eğitmeni',
    location: 'İstanbul, Beşiktaş',
    ctn: 'Vücut Geliştirme',
    seater: '1/8',
  },
  {
    id: 4,
    image: require('../../assets/group-lesson/item-4/04.jpg'),
    name: 'Selvi Özdemir',
    category: 'Salon B Fit Studio',
    price: '2000',
    star: '5',
    date: '07 Eyl. 18:00',
    content: 'Yoga Eğitmeni',
    location: 'İstanbul, Beşiktaş',
    ctn: 'Meditasyon',
    seater: '3/6',
  },
];

export const Dietitians = [
  {
    id: 1,
    image: require('../../assets/dietitians/item-1/01.jpg'),
    name: 'Nil Özgür',
    category: 'Diyetisyen',
    price: '200',
    stars: '5',
    content: 'ghfgh',
    location: 'İstanbul, Beşiktaş',
  },
  {
    id: 2,
    image: require('../../assets/dietitians/item-2/02.jpg'),
    name: 'Cenk Parlak',
    category: 'Uzman Diyetisyen',
    price: '250',
    stars: '5',
    content: '',
    location: 'İstanbul, Beşiktaş',
  },
  {
    id: 3,
    image: require('../../assets/dietitians/item-3/03.jpg'),
    name: 'Beyza Parlak',
    category: 'Diyetisyen',
    price: '260',
    stars: '5',
    content: '',
    location: 'İstanbul, Beşiktaş',
  },
  {
    id: 3,
    image: require('../../assets/dietitians/item-3/03.jpg'),
    name: 'Beyza Parlak',
    category: 'Diyetisyen',
    price: '260',
    stars: '5',
    content: '',
    location: 'İstanbul, Beşiktaş',
  },
  {
    id: 4,
    image: require('../../assets/dietitians/item-4/03.jpg'),
    name: 'Melis Gömlek',
    category: 'Dr.Diyetisyen',
    price: '180',
    stars: '5',
    content: '',
    location: 'İstanbul, Beşiktaş',
  },
];
