export const TYPES = {
    FETCH_PENDING_STEP_TWO: "FETCH_PENDING_STEP_TWO",
    FETCH_SUCCESS_STEP_TWO: "FETCH_SUCCESS_STEP_TWO",
    FETCH_LIST_SUCCESS_STEP_TWO: "FETCH_LIST_SUCCESS_STEP_TWO",
    FETCH_UPDATE_SUCCESS_STEP_TWO: "FETCH_UPDATE_SUCCESS_STEP_TWO",
    FETCH_ERROR_STEP_TWO: "FETCH_ERROR_STEP_TWO",
  };